# Generated by Django 5.0.6 on 2024-08-07 10:12

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='new_description',
        ),
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description'),
        ),
    ]
