# Generated by Django 5.0.6 on 2024-07-18 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_remove_animal_category_remove_animal_age_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_name', models.CharField(blank=True, max_length=200, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('shipping_city', models.CharField(blank=True, max_length=200, null=True)),
                ('shipping_state', models.CharField(blank=True, max_length=200, null=True)),
                ('shipping_zip', models.CharField(blank=True, max_length=200, null=True)),
                ('shipping_country', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
