# Generated by Django 5.0.6 on 2024-08-09 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_supplycategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.supplies'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.animal'),
        ),
    ]
