# Generated by Django 5.0.6 on 2024-07-18 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='shipping_country',
        ),
    ]
