# Generated by Django 5.0.6 on 2024-07-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_animal_age_animal_description_animal_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_items',
            field=models.ManyToManyField(to='Store.cartitem'),
        ),
    ]
