# Generated by Django 5.0.6 on 2024-07-22 10:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_remove_animal_age_remove_animal_sex_cart_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
