# Generated by Django 5.0.6 on 2024-07-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_alter_animal_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='age',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='sex',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
